/* Generated by Yosys 0.20+70 (git sha1 6e907acf8, clang 10.0.0-4ubuntu1 -fPIC -Os) */

(* \amaranth.hierarchy  = "wowa.wowa_digital.adc" *)
(* generator = "Amaranth" *)
module adc(use_calibration, use_external_reference, analog_comparator_pin, result, result_ready, comparator_enable_ctrl, dac_setting, calibrate, rst, clk, enable);
  reg \$auto$verilog_backend.cc:2083:dump_module$12  = 0;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:119" *)
  wire \$10 ;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:171" *)
  wire [15:0] \$101 ;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:171" *)
  wire [15:0] \$102 ;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:169" *)
  wire \$104 ;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:171" *)
  wire [15:0] \$106 ;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:171" *)
  wire [15:0] \$107 ;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:169" *)
  wire \$109 ;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:171" *)
  wire [15:0] \$111 ;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:171" *)
  wire [15:0] \$112 ;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:172" *)
  wire \$114 ;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:160" *)
  wire [2:0] \$116 ;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:160" *)
  wire [2:0] \$117 ;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:161" *)
  wire \$12 ;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:172" *)
  wire \$14 ;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:94" *)
  wire \$16 ;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:94" *)
  wire \$18 ;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:94" *)
  wire \$2 ;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:119" *)
  wire \$20 ;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:127" *)
  wire [6:0] \$22 ;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:127" *)
  wire [6:0] \$23 ;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:172" *)
  wire \$25 ;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:180" *)
  wire [6:0] \$27 ;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:180" *)
  wire [6:0] \$28 ;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:94" *)
  wire \$30 ;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:119" *)
  wire \$32 ;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:128" *)
  wire \$34 ;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:94" *)
  wire \$36 ;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:135" *)
  wire \$38 ;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:119" *)
  wire \$4 ;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:136" *)
  wire [7:0] \$40 ;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:135" *)
  wire \$42 ;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:136" *)
  wire [7:0] \$44 ;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:135" *)
  wire \$46 ;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:136" *)
  wire [7:0] \$48 ;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:135" *)
  wire \$50 ;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:136" *)
  wire [7:0] \$52 ;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:135" *)
  wire \$54 ;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:136" *)
  wire [7:0] \$56 ;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:135" *)
  wire \$58 ;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:94" *)
  wire \$6 ;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:136" *)
  wire [7:0] \$60 ;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:135" *)
  wire \$62 ;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:136" *)
  wire [7:0] \$64 ;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:135" *)
  wire \$66 ;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:136" *)
  wire [7:0] \$68 ;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:166" *)
  wire \$70 ;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:166" *)
  wire \$71 ;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:169" *)
  wire \$74 ;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:171" *)
  wire [15:0] \$76 ;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:171" *)
  wire [15:0] \$77 ;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:169" *)
  wire \$79 ;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:94" *)
  wire \$8 ;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:171" *)
  wire [15:0] \$81 ;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:171" *)
  wire [15:0] \$82 ;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:169" *)
  wire \$84 ;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:171" *)
  wire [15:0] \$86 ;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:171" *)
  wire [15:0] \$87 ;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:169" *)
  wire \$89 ;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:171" *)
  wire [15:0] \$91 ;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:171" *)
  wire [15:0] \$92 ;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:169" *)
  wire \$94 ;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:171" *)
  wire [15:0] \$96 ;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:171" *)
  wire [15:0] \$97 ;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:169" *)
  wire \$99 ;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:40" *)
  input analog_comparator_pin;
  wire analog_comparator_pin;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:49" *)
  reg calib_done = 1'h0;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:49" *)
  reg \calib_done$next ;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/comparator.py:29" *)
  output calibrate;
  reg calibrate = 1'h0;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/comparator.py:29" *)
  reg \calibrate$next ;
  (* src = "/home/malcalypse/.local/lib/python3.10/site-packages/amaranth/hdl/ir.py:527" *)
  input clk;
  wire clk;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/comparator.py:27" *)
  wire comparator_analog_comp_input;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:50" *)
  output comparator_enable_ctrl;
  wire comparator_enable_ctrl;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/comparator.py:34" *)
  wire comparator_result;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:54" *)
  output [7:0] dac_setting;
  reg [7:0] dac_setting = 8'h00;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:54" *)
  reg [7:0] \dac_setting$next ;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:41" *)
  input enable;
  wire enable;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:62" *)
  reg [5:0] internalCounter = 6'h00;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:62" *)
  reg [5:0] \internalCounter$next ;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/comparator.py:28" *)
  reg n_enable = 1'h0;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/comparator.py:28" *)
  reg \n_enable$next ;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:48" *)
  output [7:0] result;
  reg [7:0] result = 8'h00;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:48" *)
  reg [7:0] \result$next ;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:47" *)
  output result_ready;
  reg result_ready = 1'h0;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:47" *)
  reg \result_ready$next ;
  (* src = "/home/malcalypse/.local/lib/python3.10/site-packages/amaranth/hdl/ir.py:527" *)
  input rst;
  wire rst;
  (* enum_base_type = "FSMState" *)
  (* enum_value_0000 = "Startup" *)
  (* enum_value_0001 = "Idle" *)
  (* enum_value_0010 = "Calibrating" *)
  (* enum_value_0011 = "MeasureStart" *)
  (* enum_value_0100 = "MeasureSetup" *)
  (* enum_value_0101 = "MeasureDACON" *)
  (* enum_value_0110 = "MeasureHold" *)
  (* enum_value_0111 = "MeasureSample" *)
  (* enum_value_1000 = "MeasureDone" *)
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:55" *)
  reg [3:0] state = 4'h0;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:55" *)
  reg [3:0] \state$next ;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:83" *)
  reg [1:0] syncroCount = 2'h0;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:83" *)
  reg [1:0] \syncroCount$next ;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:43" *)
  input use_calibration;
  wire use_calibration;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:42" *)
  input use_external_reference;
  wire use_external_reference;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/comparator.py:30" *)
  wire \use_external_reference$1 ;
  assign \$99  = internalCounter == (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:169" *) 3'h5;
  assign \$102  = result & (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:171" *) 16'hffdf;
  assign \$104  = internalCounter == (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:169" *) 3'h6;
  assign \$107  = result & (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:171" *) 16'hffbf;
  assign \$10  = internalCounter >= (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:119" *) 6'h3c;
  assign \$109  = internalCounter == (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:169" *) 3'h7;
  assign \$112  = result & (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:171" *) 16'hff7f;
  assign \$114  = ! (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:172" *) internalCounter;
  assign \$117  = syncroCount + (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:160" *) 1'h1;
  assign \$12  = syncroCount >= (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:161" *) 2'h2;
  assign \$14  = ! (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:172" *) internalCounter;
  assign \$20  = internalCounter >= (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:119" *) 6'h3c;
  assign \$23  = internalCounter + (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:127" *) 1'h1;
  assign \$25  = ! (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:172" *) internalCounter;
  assign \$28  = internalCounter - (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:180" *) 1'h1;
  assign \$32  = internalCounter >= (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:119" *) 6'h3c;
  assign \$34  = internalCounter == (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:128" *) 6'h3b;
  assign \$38  = ! (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:135" *) internalCounter;
  assign \$40  = result | (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:136" *) 1'h1;
  assign \$42  = internalCounter == (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:135" *) 1'h1;
  assign \$44  = result | (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:136" *) 2'h2;
  assign \$46  = internalCounter == (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:135" *) 2'h2;
  assign \$48  = result | (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:136" *) 3'h4;
  assign \$4  = internalCounter >= (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:119" *) 6'h3c;
  assign \$50  = internalCounter == (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:135" *) 2'h3;
  assign \$52  = result | (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:136" *) 4'h8;
  assign \$54  = internalCounter == (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:135" *) 3'h4;
  assign \$56  = result | (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:136" *) 5'h10;
  assign \$58  = internalCounter == (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:135" *) 3'h5;
  assign \$60  = result | (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:136" *) 6'h20;
  assign \$62  = internalCounter == (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:135" *) 3'h6;
  assign \$64  = result | (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:136" *) 7'h40;
  assign \$66  = internalCounter == (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:135" *) 3'h7;
  assign \$68  = result | (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:136" *) 8'h80;
  assign \$70  = ~ (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:166" *) \$71 ;
  assign \$74  = ! (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:169" *) internalCounter;
  assign \$77  = result & (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:171" *) 16'hfffe;
  assign \$79  = internalCounter == (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:169" *) 1'h1;
  assign \$82  = result & (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:171" *) 16'hfffd;
  assign \$84  = internalCounter == (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:169" *) 2'h2;
  assign \$87  = result & (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:171" *) 16'hfffb;
  assign \$89  = internalCounter == (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:169" *) 2'h3;
  assign \$92  = result & (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:171" *) 16'hfff7;
  assign \$94  = internalCounter == (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:169" *) 3'h4;
  assign \$97  = result & (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:171" *) 16'hffef;
  always @(posedge clk)
    syncroCount <= \syncroCount$next ;
  always @(posedge clk)
    result_ready <= \result_ready$next ;
  always @(posedge clk)
    result <= \result$next ;
  always @(posedge clk)
    calib_done <= \calib_done$next ;
  always @(posedge clk)
    internalCounter <= \internalCounter$next ;
  always @(posedge clk)
    dac_setting <= \dac_setting$next ;
  always @(posedge clk)
    state <= \state$next ;
  always @(posedge clk)
    n_enable <= \n_enable$next ;
  always @(posedge clk)
    calibrate <= \calibrate$next ;
  comparator comparator (
    .analog_comp_input(comparator_analog_comp_input),
    .clk(clk),
    .result(comparator_result),
    .rst(rst)
  );
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$12 ) begin end
    \result_ready$next  = result_ready;
    (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:85" *)
    casez (state)
      /* \amaranth.decoding  = "Startup/0" */
      /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:86" */
      4'h0:
          /* empty */;
      /* \amaranth.decoding  = "Idle/1" */
      /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:93" */
      4'h1:
          /* empty */;
      /* \amaranth.decoding  = "Calibrating/2" */
      /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:117" */
      4'h2:
          \result_ready$next  = 1'h0;
      /* \amaranth.decoding  = "MeasureStart/3" */
      /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:132" */
      4'h3:
          /* empty */;
      /* \amaranth.decoding  = "MeasureSetup/4" */
      /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:147" */
      4'h4:
          /* empty */;
      /* \amaranth.decoding  = "MeasureDACON/5" */
      /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:154" */
      4'h5:
          /* empty */;
      /* \amaranth.decoding  = "MeasureHold/6" */
      /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:159" */
      4'h6:
          /* empty */;
      /* \amaranth.decoding  = "MeasureSample/7" */
      /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:165" */
      4'h7:
          (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:172" *)
          casez (\$114 )
            /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:172" */
            1'h1:
                \result_ready$next  = 1'h1;
          endcase
    endcase
    (* src = "/home/malcalypse/.local/lib/python3.10/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \result_ready$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$12 ) begin end
    \syncroCount$next  = syncroCount;
    (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:85" *)
    casez (state)
      /* \amaranth.decoding  = "Startup/0" */
      /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:86" */
      4'h0:
          /* empty */;
      /* \amaranth.decoding  = "Idle/1" */
      /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:93" */
      4'h1:
          /* empty */;
      /* \amaranth.decoding  = "Calibrating/2" */
      /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:117" */
      4'h2:
          /* empty */;
      /* \amaranth.decoding  = "MeasureStart/3" */
      /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:132" */
      4'h3:
          /* empty */;
      /* \amaranth.decoding  = "MeasureSetup/4" */
      /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:147" */
      4'h4:
          /* empty */;
      /* \amaranth.decoding  = "MeasureDACON/5" */
      /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:154" */
      4'h5:
          \syncroCount$next  = 2'h0;
      /* \amaranth.decoding  = "MeasureHold/6" */
      /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:159" */
      4'h6:
          \syncroCount$next  = \$117 [1:0];
    endcase
    (* src = "/home/malcalypse/.local/lib/python3.10/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \syncroCount$next  = 2'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$12 ) begin end
    \calibrate$next  = calibrate;
    (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:85" *)
    casez (state)
      /* \amaranth.decoding  = "Startup/0" */
      /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:86" */
      4'h0:
          \calibrate$next  = 1'h0;
      /* \amaranth.decoding  = "Idle/1" */
      /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:93" */
      4'h1:
          (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:94" *)
          casez (\$2 )
            /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:94" */
            1'h1:
                (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:100" *)
                casez (use_calibration)
                  /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:100" */
                  1'h1:
                      \calibrate$next  = 1'h1;
                endcase
          endcase
      /* \amaranth.decoding  = "Calibrating/2" */
      /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:117" */
      4'h2:
          (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:119" *)
          casez (\$4 )
            /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:119" */
            1'h1:
                \calibrate$next  = 1'h0;
          endcase
    endcase
    (* src = "/home/malcalypse/.local/lib/python3.10/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \calibrate$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$12 ) begin end
    \n_enable$next  = n_enable;
    (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:85" *)
    casez (state)
      /* \amaranth.decoding  = "Startup/0" */
      /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:86" */
      4'h0:
          \n_enable$next  = 1'h1;
      /* \amaranth.decoding  = "Idle/1" */
      /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:93" */
      4'h1:
          (* full_case = 32'd1 *)
          (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:94" *)
          casez (\$6 )
            /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:94" */
            1'h1:
                \n_enable$next  = 1'h0;
            /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:111" */
            default:
                \n_enable$next  = 1'h1;
          endcase
    endcase
    (* src = "/home/malcalypse/.local/lib/python3.10/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \n_enable$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$12 ) begin end
    \state$next  = state;
    (* full_case = 32'd1 *)
    (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:85" *)
    casez (state)
      /* \amaranth.decoding  = "Startup/0" */
      /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:86" */
      4'h0:
          \state$next  = 4'h1;
      /* \amaranth.decoding  = "Idle/1" */
      /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:93" */
      4'h1:
          (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:94" *)
          casez (\$8 )
            /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:94" */
            1'h1:
                \state$next  = 4'h2;
          endcase
      /* \amaranth.decoding  = "Calibrating/2" */
      /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:117" */
      4'h2:
          (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:119" *)
          casez (\$10 )
            /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:119" */
            1'h1:
                \state$next  = 4'h3;
          endcase
      /* \amaranth.decoding  = "MeasureStart/3" */
      /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:132" */
      4'h3:
          \state$next  = 4'h4;
      /* \amaranth.decoding  = "MeasureSetup/4" */
      /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:147" */
      4'h4:
          \state$next  = 4'h5;
      /* \amaranth.decoding  = "MeasureDACON/5" */
      /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:154" */
      4'h5:
          \state$next  = 4'h6;
      /* \amaranth.decoding  = "MeasureHold/6" */
      /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:159" */
      4'h6:
          (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:161" *)
          casez (\$12 )
            /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:161" */
            1'h1:
                \state$next  = 4'h7;
          endcase
      /* \amaranth.decoding  = "MeasureSample/7" */
      /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:165" */
      4'h7:
          (* full_case = 32'd1 *)
          (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:172" *)
          casez (\$14 )
            /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:172" */
            1'h1:
                \state$next  = 4'h8;
            /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:178" */
            default:
                \state$next  = 4'h3;
          endcase
      /* \amaranth.decoding  = "MeasureDone/8" */
      /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:183" */
      4'h8:
          \state$next  = 4'h1;
      /* \amaranth.decoding  = {0{1'b0}} */
      /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:186" */
      default:
          \state$next  = 4'h0;
    endcase
    (* src = "/home/malcalypse/.local/lib/python3.10/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \state$next  = 4'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$12 ) begin end
    \dac_setting$next  = dac_setting;
    (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:85" *)
    casez (state)
      /* \amaranth.decoding  = "Startup/0" */
      /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:86" */
      4'h0:
          /* empty */;
      /* \amaranth.decoding  = "Idle/1" */
      /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:93" */
      4'h1:
          (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:94" *)
          casez (\$16 )
            /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:94" */
            1'h1:
                \dac_setting$next  = 8'h00;
          endcase
      /* \amaranth.decoding  = "Calibrating/2" */
      /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:117" */
      4'h2:
          /* empty */;
      /* \amaranth.decoding  = "MeasureStart/3" */
      /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:132" */
      4'h3:
          /* empty */;
      /* \amaranth.decoding  = "MeasureSetup/4" */
      /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:147" */
      4'h4:
          \dac_setting$next  = result;
    endcase
    (* src = "/home/malcalypse/.local/lib/python3.10/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \dac_setting$next  = 8'h00;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$12 ) begin end
    \internalCounter$next  = internalCounter;
    (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:85" *)
    casez (state)
      /* \amaranth.decoding  = "Startup/0" */
      /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:86" */
      4'h0:
          /* empty */;
      /* \amaranth.decoding  = "Idle/1" */
      /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:93" */
      4'h1:
          (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:94" *)
          casez (\$18 )
            /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:94" */
            1'h1:
                (* full_case = 32'd1 *)
                (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:100" *)
                casez (use_calibration)
                  /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:100" */
                  1'h1:
                      \internalCounter$next  = 6'h00;
                  /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:105" */
                  default:
                      \internalCounter$next  = 6'h3c;
                endcase
          endcase
      /* \amaranth.decoding  = "Calibrating/2" */
      /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:117" */
      4'h2:
          (* full_case = 32'd1 *)
          (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:119" *)
          casez (\$20 )
            /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:119" */
            1'h1:
                \internalCounter$next  = 6'h07;
            /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:126" */
            default:
                \internalCounter$next  = \$23 [5:0];
          endcase
      /* \amaranth.decoding  = "MeasureStart/3" */
      /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:132" */
      4'h3:
          /* empty */;
      /* \amaranth.decoding  = "MeasureSetup/4" */
      /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:147" */
      4'h4:
          /* empty */;
      /* \amaranth.decoding  = "MeasureDACON/5" */
      /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:154" */
      4'h5:
          /* empty */;
      /* \amaranth.decoding  = "MeasureHold/6" */
      /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:159" */
      4'h6:
          /* empty */;
      /* \amaranth.decoding  = "MeasureSample/7" */
      /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:165" */
      4'h7:
          (* full_case = 32'd1 *)
          (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:172" *)
          casez (\$25 )
            /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:172" */
            1'h1:
                /* empty */;
            /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:178" */
            default:
                \internalCounter$next  = \$28 [5:0];
          endcase
    endcase
    (* src = "/home/malcalypse/.local/lib/python3.10/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \internalCounter$next  = 6'h00;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$12 ) begin end
    \calib_done$next  = calib_done;
    (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:85" *)
    casez (state)
      /* \amaranth.decoding  = "Startup/0" */
      /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:86" */
      4'h0:
          /* empty */;
      /* \amaranth.decoding  = "Idle/1" */
      /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:93" */
      4'h1:
          (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:94" *)
          casez (\$30 )
            /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:94" */
            1'h1:
                \calib_done$next  = 1'h0;
          endcase
      /* \amaranth.decoding  = "Calibrating/2" */
      /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:117" */
      4'h2:
          (* full_case = 32'd1 *)
          (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:119" *)
          casez (\$32 )
            /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:119" */
            1'h1:
                /* empty */;
            /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:126" */
            default:
                (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:128" *)
                casez (\$34 )
                  /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:128" */
                  1'h1:
                      \calib_done$next  = 1'h1;
                endcase
          endcase
    endcase
    (* src = "/home/malcalypse/.local/lib/python3.10/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \calib_done$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$12 ) begin end
    \result$next  = result;
    (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:85" *)
    casez (state)
      /* \amaranth.decoding  = "Startup/0" */
      /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:86" */
      4'h0:
          /* empty */;
      /* \amaranth.decoding  = "Idle/1" */
      /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:93" */
      4'h1:
          (* full_case = 32'd1 *)
          (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:94" *)
          casez (\$36 )
            /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:94" */
            1'h1:
                /* empty */;
            /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:111" */
            default:
                \result$next  = 8'h00;
          endcase
      /* \amaranth.decoding  = "Calibrating/2" */
      /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:117" */
      4'h2:
          /* empty */;
      /* \amaranth.decoding  = "MeasureStart/3" */
      /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:132" */
      4'h3:
        begin
          (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:135" *)
          casez (\$38 )
            /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:135" */
            1'h1:
                \result$next  = \$40 ;
          endcase
          (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:135" *)
          casez (\$42 )
            /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:135" */
            1'h1:
                \result$next  = \$44 ;
          endcase
          (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:135" *)
          casez (\$46 )
            /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:135" */
            1'h1:
                \result$next  = \$48 ;
          endcase
          (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:135" *)
          casez (\$50 )
            /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:135" */
            1'h1:
                \result$next  = \$52 ;
          endcase
          (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:135" *)
          casez (\$54 )
            /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:135" */
            1'h1:
                \result$next  = \$56 ;
          endcase
          (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:135" *)
          casez (\$58 )
            /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:135" */
            1'h1:
                \result$next  = \$60 ;
          endcase
          (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:135" *)
          casez (\$62 )
            /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:135" */
            1'h1:
                \result$next  = \$64 ;
          endcase
          (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:135" *)
          casez (\$66 )
            /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:135" */
            1'h1:
                \result$next  = \$68 ;
          endcase
        end
      /* \amaranth.decoding  = "MeasureSetup/4" */
      /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:147" */
      4'h4:
          /* empty */;
      /* \amaranth.decoding  = "MeasureDACON/5" */
      /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:154" */
      4'h5:
          /* empty */;
      /* \amaranth.decoding  = "MeasureHold/6" */
      /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:159" */
      4'h6:
          /* empty */;
      /* \amaranth.decoding  = "MeasureSample/7" */
      /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:165" */
      4'h7:
          (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:166" *)
          casez (\$70 )
            /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:166" */
            1'h1:
              begin
                (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:169" *)
                casez (\$74 )
                  /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:169" */
                  1'h1:
                      \result$next  = \$77 [7:0];
                endcase
                (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:169" *)
                casez (\$79 )
                  /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:169" */
                  1'h1:
                      \result$next  = \$82 [7:0];
                endcase
                (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:169" *)
                casez (\$84 )
                  /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:169" */
                  1'h1:
                      \result$next  = \$87 [7:0];
                endcase
                (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:169" *)
                casez (\$89 )
                  /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:169" */
                  1'h1:
                      \result$next  = \$92 [7:0];
                endcase
                (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:169" *)
                casez (\$94 )
                  /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:169" */
                  1'h1:
                      \result$next  = \$97 [7:0];
                endcase
                (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:169" *)
                casez (\$99 )
                  /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:169" */
                  1'h1:
                      \result$next  = \$102 [7:0];
                endcase
                (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:169" *)
                casez (\$104 )
                  /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:169" */
                  1'h1:
                      \result$next  = \$107 [7:0];
                endcase
                (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:169" *)
                casez (\$109 )
                  /* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:169" */
                  1'h1:
                      \result$next  = \$112 [7:0];
                endcase
              end
          endcase
    endcase
    (* src = "/home/malcalypse/.local/lib/python3.10/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \result$next  = 8'h00;
    endcase
  end
  assign \$22  = \$23 ;
  assign \$27  = \$28 ;
  assign \$76  = \$77 ;
  assign \$81  = \$82 ;
  assign \$86  = \$87 ;
  assign \$91  = \$92 ;
  assign \$96  = \$97 ;
  assign \$101  = \$102 ;
  assign \$106  = \$107 ;
  assign \$111  = \$112 ;
  assign \$116  = \$117 ;
  assign comparator_enable_ctrl = n_enable;
  assign \use_external_reference$1  = use_external_reference;
  assign comparator_analog_comp_input = analog_comparator_pin;
  assign \$2  = enable;
  assign \$6  = enable;
  assign \$8  = enable;
  assign \$16  = enable;
  assign \$18  = enable;
  assign \$30  = enable;
  assign \$36  = enable;
  assign \$71  = comparator_result;
endmodule

(* \amaranth.hierarchy  = "wowa.wowa_digital.adc.comparator" *)
(* generator = "Amaranth" *)
module comparator(result, rst, clk, analog_comp_input);
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/comparator.py:27" *)
  input analog_comp_input;
  wire analog_comp_input;
  (* src = "/home/malcalypse/.local/lib/python3.10/site-packages/amaranth/hdl/ir.py:527" *)
  input clk;
  wire clk;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/comparator_result.py:27" *)
  wire compres_input;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/comparator_result.py:28" *)
  wire compres_output;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/comparator.py:34" *)
  output result;
  wire result;
  (* src = "/home/malcalypse/.local/lib/python3.10/site-packages/amaranth/hdl/ir.py:527" *)
  input rst;
  wire rst;
  compres compres (
    .clk(clk),
    .\input (compres_input),
    .\output (compres_output),
    .rst(rst)
  );
  assign result = compres_output;
  assign compres_input = analog_comp_input;
endmodule

(* \amaranth.hierarchy  = "wowa.wowa_digital.adc.comparator.compres" *)
(* generator = "Amaranth" *)
module compres(clk, \input , \output , rst);
  (* src = "/home/malcalypse/.local/lib/python3.10/site-packages/amaranth/hdl/ir.py:527" *)
  input clk;
  wire clk;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/comparator_result.py:27" *)
  input \input ;
  wire \input ;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/comparator_result.py:28" *)
  output \output ;
  wire \output ;
  (* src = "/home/malcalypse/.local/lib/python3.10/site-packages/amaranth/hdl/ir.py:527" *)
  input rst;
  wire rst;
  ffsync ffsync (
    .clk(clk),
    .\input (\input ),
    .\output (\output ),
    .rst(rst)
  );
endmodule

(* \amaranth.hierarchy  = "wowa.wowa_digital.adc.comparator.compres.ffsync" *)
(* generator = "Amaranth" *)
module ffsync(clk, \input , \output , rst);
  (* src = "/home/malcalypse/.local/lib/python3.10/site-packages/amaranth/hdl/ir.py:527" *)
  input clk;
  wire clk;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/comparator_result.py:27" *)
  input \input ;
  wire \input ;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/comparator_result.py:28" *)
  output \output ;
  wire \output ;
  (* src = "/home/malcalypse/.local/lib/python3.10/site-packages/amaranth/hdl/ir.py:527" *)
  input rst;
  wire rst;
  (* src = "/home/malcalypse/.local/lib/python3.10/site-packages/amaranth/lib/cdc.py:89" *)
  reg stage0 = 1'h0;
  (* src = "/home/malcalypse/.local/lib/python3.10/site-packages/amaranth/lib/cdc.py:89" *)
  wire \stage0$next ;
  (* src = "/home/malcalypse/.local/lib/python3.10/site-packages/amaranth/lib/cdc.py:89" *)
  reg stage1 = 1'h0;
  (* src = "/home/malcalypse/.local/lib/python3.10/site-packages/amaranth/lib/cdc.py:89" *)
  wire \stage1$next ;
  always @(posedge clk)
    stage1 <= stage0;
  always @(posedge clk)
    stage0 <= \input ;
  assign \output  = stage1;
  assign \stage1$next  = stage0;
  assign \stage0$next  = \input ;
endmodule

(* \amaranth.hierarchy  = "wowa" *)
(* top =  1  *)
(* generator = "Amaranth" *)
module wowa(analog_comparator_out, do_calibrate, use_ext_thresh, result_ready, result, dac_set, comparator_nen, calib_enable, thresh_sel, clk, rst, user_enable);
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/wowa_digital.py:58" *)
  input analog_comparator_out;
  wire analog_comparator_out;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/wowa_digital.py:60" *)
  input calib_enable;
  wire calib_enable;
  (* src = "/home/malcalypse/.local/lib/python3.10/site-packages/amaranth/hdl/ir.py:527" *)
  input clk;
  wire clk;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/wowa_digital.py:68" *)
  output comparator_nen;
  wire comparator_nen;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/wowa_digital.py:67" *)
  output [7:0] dac_set;
  wire [7:0] dac_set;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/wowa_digital.py:71" *)
  output do_calibrate;
  wire do_calibrate;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/wowa_digital.py:66" *)
  output [7:0] result;
  wire [7:0] result;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/wowa_digital.py:65" *)
  output result_ready;
  wire result_ready;
  (* src = "/home/malcalypse/.local/lib/python3.10/site-packages/amaranth/hdl/ir.py:527" *)
  input rst;
  wire rst;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/wowa_digital.py:70" *)
  output thresh_sel;
  wire thresh_sel;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/wowa_digital.py:59" *)
  input use_ext_thresh;
  wire use_ext_thresh;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/wowa_digital.py:57" *)
  input user_enable;
  wire user_enable;
  wowa_digital wowa_digital (
    .analog_comparator_out(analog_comparator_out),
    .calib_enable(calib_enable),
    .clk(clk),
    .comparator_nen(comparator_nen),
    .dac_set(dac_set),
    .do_calibrate(do_calibrate),
    .result(result),
    .result_ready(result_ready),
    .rst(rst),
    .thresh_sel(thresh_sel),
    .use_ext_thresh(use_ext_thresh),
    .user_enable(user_enable)
  );
endmodule

(* \amaranth.hierarchy  = "wowa.wowa_digital" *)
(* generator = "Amaranth" *)
module wowa_digital(calib_enable, use_ext_thresh, analog_comparator_out, result, result_ready, comparator_nen, dac_set, do_calibrate, thresh_sel, rst, clk, user_enable);
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:40" *)
  wire adc_analog_comparator_pin;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/comparator.py:29" *)
  wire adc_calibrate;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:50" *)
  wire adc_comparator_enable_ctrl;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:54" *)
  wire [7:0] adc_dac_setting;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:41" *)
  wire adc_enable;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:48" *)
  wire [7:0] adc_result;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:47" *)
  wire adc_result_ready;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:43" *)
  wire adc_use_calibration;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/adc.py:42" *)
  wire adc_use_external_reference;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/wowa_digital.py:58" *)
  input analog_comparator_out;
  wire analog_comparator_out;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/wowa_digital.py:60" *)
  input calib_enable;
  wire calib_enable;
  (* src = "/home/malcalypse/.local/lib/python3.10/site-packages/amaranth/hdl/ir.py:527" *)
  input clk;
  wire clk;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/wowa_digital.py:68" *)
  output comparator_nen;
  wire comparator_nen;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/wowa_digital.py:67" *)
  output [7:0] dac_set;
  wire [7:0] dac_set;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/wowa_digital.py:71" *)
  output do_calibrate;
  wire do_calibrate;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/wowa_digital.py:66" *)
  output [7:0] result;
  wire [7:0] result;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/wowa_digital.py:65" *)
  output result_ready;
  wire result_ready;
  (* src = "/home/malcalypse/.local/lib/python3.10/site-packages/amaranth/hdl/ir.py:527" *)
  input rst;
  wire rst;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/wowa_digital.py:70" *)
  output thresh_sel;
  wire thresh_sel;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/wowa_digital.py:59" *)
  input use_ext_thresh;
  wire use_ext_thresh;
  (* src = "/storage/malcalypse/vm/vmswap/ttuserwork/tt06-wowa/digitalsrc/wowa/wowa_digital.py:57" *)
  input user_enable;
  wire user_enable;
  adc adc (
    .analog_comparator_pin(adc_analog_comparator_pin),
    .calibrate(adc_calibrate),
    .clk(clk),
    .comparator_enable_ctrl(adc_comparator_enable_ctrl),
    .dac_setting(adc_dac_setting),
    .enable(adc_enable),
    .result(adc_result),
    .result_ready(adc_result_ready),
    .rst(rst),
    .use_calibration(adc_use_calibration),
    .use_external_reference(adc_use_external_reference)
  );
  assign thresh_sel = use_ext_thresh;
  assign do_calibrate = adc_calibrate;
  assign dac_set = adc_dac_setting;
  assign comparator_nen = adc_comparator_enable_ctrl;
  assign result_ready = adc_result_ready;
  assign result = adc_result;
  assign adc_analog_comparator_pin = analog_comparator_out;
  assign adc_use_external_reference = use_ext_thresh;
  assign adc_use_calibration = calib_enable;
  assign adc_enable = user_enable;
endmodule

